### ISSUE TITLE
duplicate test repo?

### ISSUE THREAD

**Issue by ungoldman** [jgravois/koop-heroku-rest#1]
do we want to roll this into https://github.com/chelm/heroku-koop-deploy/issues/1 as well? one koop-heroku example to rule them all?

**Comment by jgravois** [comment]
i made this one so i could [hardcode](https://github.com/jgravois/koop-heroku-rest/blob/master/package.json#L18) a dependency on a bug fix i shimmed [here](https://github.com/jgravois/koop-github/tree/add-rest).

i don't have any other repos that would be beneficial to port, theyre mostly just false starts.
